### PR TITLE
meson: fix argp-standalone wrap and find_library

### PR DESCRIPTION
**Pull request by jameshilliard**
Currently using my own fork of [`argp-standalone`](https://github.com/argp-standalone/argp-standalone) with a few fixes I submitted upstream [here](https://github.com/argp-standalone/argp-standalone/pull/7) but should fix the wrap build on windows.

### CODE REVIEW

**Comment by jameshilliard** [comment]
FYI there's a [github setting](https://github.com/zchunk/zchunk/settings) you can change so that you don't have to manually approve workflows most of the time:
Screen Shot 2022-04-22 at 12 17 36 PM

**Comment by jdieter** [comment]
> FYI there's a [github setting](https://github.com/zchunk/zchunk/settings) you can change so that you don't have to manually approve workflows most of the time: Screen Shot 2022-04-22 at 12 17 36 PM

I've sorted this out.  Thanks for the tip!

**Comment by jdieter** [comment]
@wolfv, this patch works.  Will you be merging your changes upstream any time soon?  Because, if not, I think I'll merge this.

**Comment by wolfv** [comment]
Merged!

**Comment by jameshilliard** [comment]
Wrap now pointing to:
```
url = https://github.com/argp-standalone/argp-standalone.git
revision = 21855f34ec9997c37e1a08cd69497336513a5800
```

**Pull request merged**
