### PR TITLE
meson: add option to build without docs

### PR DESCRIPTION
**Pull request by jameshilliard**
Useful for distributions such as [buildroot](https://buildroot.org/) that don't want documentation built.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Nothing is being built, though, just copied to the target. So why is this option necessary?

Shouldn't buildroot e.g. have an automatic cleanup pass to prune `/usr/share/man/` in order to reduce size usage?

It would make more sense to have a project option, if the man pages were built with asciidoc or doxygen or xsltproc or something, as this would help reduce pointless dependencies and save build steps.

It is also possible since Meson 0.60.0 to only install a subset of a project, see https://mesonbuild.com/Installing.html#installation-tags for details.

**Comment by jameshilliard** [comment]
> Shouldn't buildroot e.g. have an automatic cleanup pass to prune `/usr/share/man/` in order to reduce size usage?

Yeah, although we prefer to disable installation entirely if possible.

> It is also possible since Meson 0.60.0 to only install a subset of a project, see https://mesonbuild.com/Installing.html#installation-tags for details.

Oh that's interesting, is there a way to negate a specific tag like man/doc instead of having to specify tags one wants to include?

**Comment by eli-schwartz** [comment]
> Yeah, although we prefer to disable installation entirely if possible.

Is there a reason for this preference, or does it just save a few cycles due to not copying files you intend to delete anyway, or... ?

(Basically, why is it worth the complexity of adding an upstream option for this?)

> Oh that's interesting, is there a way to negate a specific tag like man/doc instead of having to specify tags one wants to include?

Currently, no. Discussion welcome on the Meson issue tracker if you'd like to fine-tune the way it is/can be used. :)

**Comment by jameshilliard** [comment]
> Is there a reason for this preference, or does it just save a few cycles due to not copying files you intend to delete anyway, or... ?

It's standard practice for us at least to always try and disable this stuff when possible, reduces chance of hitting any potential issues and makes it easier to trace what's getting installed if we can prevent unwanted artifacts from being installed, it's not a huge issue but the ability to disable docs explicitly like this seems to fairly common for meson based projects.

> (Basically, why is it worth the complexity of adding an upstream option for this?)

Well it's probably more of an issue if upstream projects add docs stuff that requires additional dependencies(like custom stuff that generates docs from templates using external tools for example), if the option to disable them is there then those requirements should get suppressed(if guarded properly).

> Currently, no. Discussion welcome on the Meson issue tracker if you'd like to fine-tune the way it is/can be used. :)

Ok, I'll see if I can add tags support to [buildroot](https://buildroot.org/) without negating and see if it's workable as is first.

**Comment by jdieter** [comment]
> > Currently, no. Discussion welcome on the Meson issue tracker if you'd like to fine-tune the way it is/can be used. :)
> 
> Ok, I'll see if I can add tags support to [buildroot](https://buildroot.org/) without negating and see if it's workable as is first.

FWIW, the tags support would be ideal, but, if that won't work, I'm happy to merge this.

**Comment by jameshilliard** [comment]
> FWIW, the tags support would be ideal, but, if that won't work, I'm happy to merge this.

I'd say still good to have for now at least since tags isn't exactly a direct replacement for this sort of option.

**Pull request merged**
