### PR TITLE
Stop storing last error when missing zchunk context

### LINKED ISSUE #106: Thread safe API
We have been seeing crashes in `createrepo_c` due to its multi-threading nature.

See: https://github.com/rpm-software-management/createrepo_c/issues/386

Would it be possible to make the API thread safe or is this something we have to work around in `createrepo_c`?

### PR DESCRIPTION
**Pull request by jdieter**
Originally, when a null zchunk context was passed into the error logging functions, we stored the error information in a global context called `zck_none`.  While this worked perfectly for single-threaded operations, multiple threads, even if operating on different files, would intermittently fail (for an example, see
https://github.com/rpm-software-management/createrepo_c/issues/386).

This PR removes this "feature".  Now, when a null zchunk context is passed to "create" the error, we output the error message, but don't do anything else.  Running `zck_get_error(NULL)` will always return an empty string and running `zck_clear_error(NULL)` is a noop.  `zck_is_error(NULL)` will always return 0.

We also remove everywhere in our code that we were running `zck_get_error(NULL)` and `zck_clear_error(NULL)`, since they're noops.

The reality is that the only way to not have a zchunk context is if we weren't able to allocate it, so I expect this to have no effect on any users of the library.

This makes the library thread-safe, as long as each context is only touched in a single thread.

Fixes #106

### CODE REVIEW

**Comment by jdieter** [comment]
@kontura, would you mind taking a look at this?  If you could build this branch and use it for the `createrepo_c` test suite, I'd like to make sure this actually fixes the problem before I merge it.

**Comment by kontura** [comment]
> @kontura, would you mind taking a look at this?  If you could build this branch and use it for the `createrepo_c` test suite, I'd like to make sure this actually fixes the problem before I merge it.

Sure, but I am off for the next 7 days so if you don't mind waiting a bit.

**Comment by jdieter** [comment]
> > @kontura, would you mind taking a look at this?  If you could build this branch and use it for the `createrepo_c` test suite, I'd like to make sure this actually fixes the problem before I merge it.
> 
> Sure, but I am off for the next 7 days so if you don't mind waiting a bit.

Yep, no problem!

**Comment by kontura** [comment]
> @kontura, would you mind taking a look at this? If you could build this branch and use it for the `createrepo_c` test suite, I'd like to make sure this actually fixes the problem before I merge it.

I have tested it and I cannot reproduce the problem with this patch so I believe it fixes it.
Thank you for working on this.

**Pull request merged**
