### PR TITLE
Fixed meson for static build on windows

### PR DESCRIPTION
**Pull request by JohanMabille**

### CODE REVIEW

**Comment by JohanMabille** [comment]
The issue seems unrelated to the change.

**Comment by jdieter** [comment]
Yep, the CI failure is unrelated.  Would you mind adding a test for this so we can make sure that we don't break the static linking in Windows at a later point?

**Review by jdieter — APPROVED** [review]

**Comment by jdieter** [comment]
@JohanMabille, thanks so much for the added test and for this PR.  I've just released zchunk-1.2.3 with these changes included.

**Comment by JohanMabille** [comment]
Thanks for the quick release ;)

**Pull request merged**
