### PR TITLE
Add REG_ENHANCED to regcomp for OSX

### LINKED ISSUE #32: OSX regex issue
We are trying to use zchunk to download repodata in https://github.com/mamba-org/mamba/pull/615. It works fine for Linux but on OSX we get an error `create_regex: Unable to compile regular expression`: https://github.com/mamba-org/mamba/pull/615/checks?check_run_id=1500220314.
I'm not sure what's going on. If you have any idea about what the cause could be, or how to debug it, that would be great.

### PR DESCRIPTION
**Pull request by davidbrochart**
Fixes #32

### CODE REVIEW

**Comment by jdieter** [comment]
Thanks for looking into this and providing a patch!

**Comment by davidbrochart** [comment]
@jdieter do you think you can make a release? We would need that to have the conda-forge package working on OSX.

**Comment by jdieter** [comment]
> @jdieter do you think you can make a release? We would need that to have the conda-forge package working on OSX.

Done.

**Comment by davidbrochart** [comment]
Awesome, thanks!

**Pull request merged**
