### PR TITLE
Rework hash code to support openSSL 3.x EVP API

### PR DESCRIPTION
**Pull request by mattwood-microchip**
Reorganize hash code to support either openSSL API or bundled sha code. This also allows other digest libraries to be added in the future.

Add meson option for deprecated openSSL 1.x API compatibility.

### CODE REVIEW

**Comment by mattwood-microchip** [comment]
Looks like the centos7 test failed due to openSSL 3.x API being set as default in the meson options.  Should the deprecated API be set by default instead, or require centos7 and other users of openssl 1.x to manually set the the deprecated build option?

**Comment by jdieter** [comment]
Since meson can detect the installed OpenSSL version, can we have it
automatically set the necessary defines rather than using a build option?

**Comment by mattwood-microchip** [comment]
yup, i'll push that change

**Comment by mattwood-microchip** [comment]
ok looks like all tests passed except I'm not sure why linters is failing on libsha.h, there is a new line at the end.

**Comment by jdieter** [comment]
It looks like there's one too many newlines at the end of the file. :grin:

**Comment by jdieter** [comment]
Other than that, I think the PR looks great!

**Comment by mattwood-microchip** [comment]
well that would be why! :)

Just pushed that fix and and all tests passed

**Review by jdieter — APPROVED** [review]

**Comment by jdieter** [comment]
That's merged now

**Comment by mattwood-microchip** [comment]
Thanks!  I'll have some more PRs shortly

**Pull request merged**
