### PR TITLE
meson: fix argp-standalone find_library

### PR DESCRIPTION
**Pull request by jameshilliard**
I think this is more correct compared with #75.

### CODE REVIEW

**Comment by jdieter** [comment]
Unfortunately, while I do like this PR's simplicity, it fails when building on Windows.

**Comment by jdieter** [comment]
Well, nevermind.  It looks like even the `main` branch has broken in Windows in the last few days.

**Comment by jameshilliard** [comment]
> It looks like even the `main` branch has broken in Windows in the last few days.

Fixed the windows wrap issue in #78 although that currently depends on some unmerged [upstream argp-standalone fixes](https://github.com/argp-standalone/argp-standalone/pull/7) at the moment.

**Comment by jdieter** [comment]
Am I correct in thinking I can close this?  That this was included in your other PR?

**Comment by jameshilliard** [comment]
> Am I correct in thinking I can close this?

Yes, closing as it is now superseded by the merged #78.

**Pull request closed without merging**
